cloud-init + DHCP Server
Ashtoruin/pibernetes pull request #1
Opened 2020-09-17 12:04 UTC by Ashtoruin

Installs cloud-init
sets up my user
sets up DHCP server for eth0

2020-09-17 12:07 UTC, Ashtoruin commented on boot/user-data
> +    lock_passwd: false
this should be true

2020-09-17 12:07 UTC, Ashtoruin commented on boot/meta-data
> +  broadcast 10.0.0.0
netmask doesn't get populated so we should remove it

2020-09-17 12:07 UTC, Ashtoruin commented on etc/cloud/cloud.cfg
> +disable_root: false
should probs disable this

2020-09-17 12:37 UTC, matthew-dawson requested changes

2020-09-17 12:37 UTC, matthew-dawson commented on boot/cloud-init-setup.sh
> +#sudo debconf-set-selections -v <<<"cloud-init cloud-init/datasources multiselect NoCloud, None" 2>/dev/null; sudo dpkg-reconfigure cloud-init -f noninteractive 2>/dev/null;
Is the dpkg-reconfigure a hold-over from the original script and just not required?

2020-09-17 12:37 UTC, matthew-dawson commented on boot/cloud-init-setup.sh
> +# /boot/user-data
These seem to be placeholders or notes indicating to create the respective files, which are created elsewhere in this pull request.  If these comments are to remain, I suggest updating them to denote that these are the default paths for the config, meta-data, and user-data respectively; although the default locations are denoted within the cloud-init documentation, so I'm not certain this is needed.

2020-09-17 12:37 UTC, matthew-dawson commented on boot/cloud-init-setup.sh
> +         /boot/per-once/02_install_stuff.sh <<'BASH'
Just me being pedantic, but this looks like a copy pasta.  I suggest updating the names of the scripts to something more permanent (i.e. /boot/per-boot/01_initialize.sh, /boot/per-boot/02_execute.sh, /boot/per-once/01_initialize.sh, /boot/per-once/02_install_app_name.sh)

I can see value in populating these files with sample data for modification in the future, however you may wish to track that these files are present and need to be updated via a ticket or something so that you don't just end up shipping sample code or useless cruft.

2020-09-17 12:37 UTC, matthew-dawson commented on boot/cloud-init-setup.sh
> +echo "$date - $script_name" >> /home/pi/${log_name}.out
I suggest keeping log files in /var/log rather than sending them to the /home/pi user directory

2020-09-17 12:37 UTC, matthew-dawson commented on boot/meta-data
> +  broadcast 10.0.0.0
How does cloud-init determine the correct netmask for the given IP address if it's not being populated?

Seeing as this is populating /etc/network/interfaces with the values for the eth0 interface, have you tried removing the /etc/dhcp/dhcpcd.conf configuration for statically assigning eth0 the ip address and verifying that everything still works as expected?  It seems that you may have two subsystems trying to set the network config for eth0 at the moment (network-interfaces and dhcpcd).

2020-09-17 12:37 UTC, matthew-dawson commented on boot/meta-data
> +  address 10.0.0.0
Did you intend for the kubernetes-master node to be assigned the IP address of .0 rather than .1?  (10.0.0.1)

2020-09-17 12:37 UTC, matthew-dawson commented on boot/user-data
> +      metric 400
Looks as though you're specifying the eth0 network configuration here as well as within /etc/network/interfaces (and they're not the same IP addresses).  Need to determine one place to facilitate the network configuration of eth0 and stick with it rather than maintaining it in two different locations.

2020-09-17 12:46 UTC, Ashtoruin commented on boot/cloud-init-setup.sh
> +# /boot/user-data
Still deciding how we want to install all of this and forgot to delete these as part of cleaning things up.  I'll probably just delete these and figure that out in the future since all these files need to exist.

2020-09-17 12:49 UTC, Ashtoruin commented on boot/meta-data
> +  broadcast 10.0.0.0
I think you're probably right with dhcpcd.conf doing some magic over this. I'm honestly just considering disabling the cloud-init network conf because it doesn't seem to be well... documented... at all... or do all the things we want.

2020-09-18 09:09 UTC, Ashtoruin commented
We've decided that cloud-init while neat is probably not the right tool for configuring the master node and thus are moving to ansible. We will reconsider this for the worker nodes.

2020-09-18 09:10 UTC, closed without merging